export enum AreaTypes {
  Total = 'total',
  Interior = 'interior',
  Exterior = 'exterior',
}



export enum AreaUnits {
  M2 = 'm²',
  FT = 'ft²',
}



export enum CurrencyCodes {
  GBP = 'GBP',
  AED = 'AED',
}


 enum UnitStates {
  Floorplan = 'floorplan',
  Interior = 'interior',
  UnitViews = 'unit-views',
}


enum ViewConfigType {
  Unit = 'Unit',
  Variant = 'Variant',
  UnitView = 'UnitView',
}


interface IProjectConfig {
  hasSchemes?: boolean;
  variantsWithSchemes?: string[];
  hasPoolOption?: boolean;
  hasPodOption?: boolean;
  unitDefaultState?: UnitStates;
  exteriorViewConfigType?: ViewConfigType;
  floorplanViewConfigType?: ViewConfigType;
  interiorViewConfigTypes?: ViewConfigType[];
  externalRequestCallback?: string;
  displayNameMap?: Record<string, string>;
  brochureDownloadAvailabilityMap?: Record<string, boolean>;
  hasExteriorViews?: boolean;
  propertyTypeDisplayNameMap?: Record<string, string>;
  displayedAreas: AreaTypes[];
  showAlternativeAreaUnit: boolean;
  currencyCode: CurrencyCodes;
  areaUnit: AreaUnits;
  variantFloorCounts?: Record<string, number>;
  variantDefaultFloors?: Record<string, number>;
}

const PROJECT_BROCHURE_DOWNLOAD_KEY = 'project';

const normalizeBrochureCode = (code?: string) =>
  code?.toLowerCase().replace(/[-_\s]/g, '');

export const VERDES_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {verdes: 'Verdes \nby Haven'},
};

export const WESTMINSTER_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.GBP,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  //externalRequestCallback: 'https://thewestminstertower.co.uk/',
  externalRequestCallback:'',
  displayNameMap: {westminstertower: 'Westminster Tower'},
  brochureDownloadAvailabilityMap: {
    [PROJECT_BROCHURE_DOWNLOAD_KEY]: true,
    westminstertower: true,
  },
};

export const ALMARJAN_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  variantsWithSchemes: ['B_S_5BF_SV1', 'B_S_5B_SV2', 'B_S_5B_SV3'],
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    'b1': 'Nikki Beach Tower B1',
    'b2': 'Nikki Beach Tower B2',
    'b3': 'Nikki Beach Tower B3',
    'r1': 'Rosso Bay Tower R1',
    'r2': 'Rosso Bay Tower R2',
    'r3': 'Rosso Bay Tower R3',
    'almarjan': 'Al Marjan Residences',
    'almarjan-nikkibeach': 'Nikki Beach',
    'almarjan-rossobay': 'Rosso Bay',
  },
};
export const HAVEN_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Variant],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  showAlternativeAreaUnit: false,
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
};

export const ATHLON_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  showAlternativeAreaUnit: false,
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
};

export const RISEBYATHLON_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    risebyathlon: 'Rise By Athlon',
    neon: 'Neon',
    cyan: 'Cyan',
    azul: 'Azul',
    teal: 'Teal',
    magenta: 'Magenta',
    tempo: 'Tempo',
    grid: 'Grid',
    foundry: 'Foundry',
  },
};

export const MAMSHAPALM_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  showAlternativeAreaUnit: false,
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  externalRequestCallback: '',
  displayNameMap: {mamshapalm: 'Mamsha Palm'},
};

export const MAMSHAGARDEN_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  showAlternativeAreaUnit: false,
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  externalRequestCallback: '',
  displayNameMap: {mamshagarden: 'Mamsha Garden'},
};

export const THEARTHOUSE_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  showAlternativeAreaUnit: false,
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  displayNameMap: {thearthouse: 'The Arthouse'},
};

export const GROVE_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  showAlternativeAreaUnit: false,
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  displayNameMap: {
    grove: 'Saadiyat Grove',
    heart1: 'Grove\n Beach\n Views',
    heart2: 'Grove\n Uptown\n Views',
    heart3: 'Grove\n Gallery\n Views',
    heart4: 'Grove\n Fountain\n Views',
    heart5: 'Grove\n Museum\n Views',
  },
};

export const YASRIVA_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: true,
  hasPodOption: true,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  showAlternativeAreaUnit: false,
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  displayNameMap: {
    yasriva: 'Yas Riva',
    yn7: 'Community',
  },
};

export const YASRIVARESIDENCES_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total],
  showAlternativeAreaUnit: false,
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  displayNameMap: {
    yasrivaresidences: 'Yas Riva Residences',
    b1: 'Onda',
    b2: 'Fonte',
    b3: 'Clara',
    b4: 'Baia',
    b5: 'Ancor',
    b6: 'Ventus',
  },
};

export const SCD_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  showAlternativeAreaUnit: false,
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  displayNameMap: {
    guggenheimmuseum: 'Guggenheim Museum',
    businessdistrict: 'Business District',
    fountaindistrict: 'Fountain District',
    grovedistrict: 'Grove District',
    artisandistrict: 'Artisan District',
    mamshadistrict: 'Mamsha Boulevard',
    lifestyledistrict: 'Lifestyle District',
    pulsedistrict: 'Pulse District',
    abrahamicfamilyhouse: 'Abrahamic Family House',
    centerofcuriosity: 'Center Of Curiosity',
    louvre: 'Louvre',
    manaratgallery: 'Manarat Gallery',
    naturalhistorymuseum: 'Natural History Museum',
    pier: 'Saadiyat Pier',
    zayedmuseum: 'Zayed Museum',
  },
};

export const FAHIDISLAND_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  showAlternativeAreaUnit: false,
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  displayNameMap: {
    waterfrontpromenade: 'Waterfront Promenade',
    coraldrive: 'Coral Drive',
    theberm: 'The Berm',
  },
};

export const TWICKENHAMSQUARE_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.GBP,
  areaUnit: AreaUnits.FT,
  showAlternativeAreaUnit: false,
  //externalRequestCallback:'https://londonsquare.co.uk/developments/twickenham-square?woa#genericForm',
  externalRequestCallback:'',
  displayNameMap: {
    twickenhamsquare: 'Twickenham\n Square',
    rosesquare: 'Rose Square',
    millhouse: 'Mill House',
    ashhouse: 'Ash House',
    cranefordhouse: 'Craneford House',
    rivierahouse: 'Riviera House',
  },
  brochureDownloadAvailabilityMap: {
    [PROJECT_BROCHURE_DOWNLOAD_KEY]: true,
    ashhouse: true,
    cranefordhouse: true,
    millhouse: true,
    rivierahouse: true,
    rosesquare: true,
  },
};

export const TWICKENHAMGREEN_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  showAlternativeAreaUnit: false,
  currencyCode: CurrencyCodes.GBP,
  areaUnit: AreaUnits.FT,
  //externalRequestCallback:'https://londonsquare.co.uk/developments/twickenham-green?woa#genericForm',
  externalRequestCallback:'',
  displayNameMap: {
    twickenhamgreen: 'Twickenham\n Green',
    cranehouse: 'Crane House',
    bakersmewsnorth: 'Bakers Mews\n North',
    bakersmewseast: 'Bakers Mews\n East',
    bakersmewswest: 'Bakers Mews\n West',
  },
  brochureDownloadAvailabilityMap: {
    [PROJECT_BROCHURE_DOWNLOAD_KEY]: true,
    bakersmewseast: true,
    bakersmewsnorth: true,
    bakersmewswest: true,
    cranehouse: true,
  },
};

export const FAYAALSAADIYAT_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {fayaalsaadiyat: 'Faya Al Saadiyat', sb45: 'Community'},
};

export const WANDSWORTHCOMMON_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.GBP,
  areaUnit: AreaUnits.FT,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    wandsworthcommon: 'Wandsworth\n Common',
    b1: 'The Townhouses',
    b2: 'Hawthorn Apartments',
    b3: 'Birch Apartments',
    b4: 'Willow Apartments',
    b5: 'The Residences',
    b6: 'Beech Apartments',
  },
  brochureDownloadAvailabilityMap: {
    [PROJECT_BROCHURE_DOWNLOAD_KEY]: true,
    b1: true,
    b2: true,
    b3: true,
    b4: true,
    b5: true,
    b6: true,
  },
};

export const FOUNTAINVIEWRESIDENCES_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    fountainviewresidences: 'Mandarin Oriental Residences',
    b1: 'North Tower',
    b2: 'South Tower',
  },
};

export const FAYAALSAADIYATII_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {fayaalsaadiyatii: 'Faya Vista', sdn2: 'Community'},
};

export const FAHIDBEACHRESIDENCES_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    fahidbeachresidences: 'Fahid Beach Residences',
    b1: 'Tower B1',
    b2: 'Tower B2',
    b3: 'Tower B3',
    b4: 'Tower B4',
    b5: 'Tower B5',
    b6: 'Tower B6',
    b7: 'Tower B7',
  },
};

export const FAHIDBEACHTERRACES_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    fahidbeachterraces: 'Fahid Beach Terraces',
    b1: 'Tower B1',
    b2: 'Tower B2',
    b3: 'Tower B3',
    b4: 'Tower B4',
    b5: 'Tower B5',
    b6: 'Tower B6',
  },
};

export const THEBEACHHOUSE_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    thebeachhouse: 'The Beach House',
    b1: 'Tower 1',
    b2: 'Tower 2',
    b3: 'Tower 3',
    b4: 'Tower 4',
    b5: 'Tower 5',
    b6: 'Tower 6',
    b7: 'Tower 7',
    b8: 'Tower 8',
    b9: 'Tower 9',
    b10: 'Tower 10',
    b11: 'Tower 11',
  },
};

export const THEBEACHHOUSE2_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    thebeachhouse2: 'The Beach House 2',
    a1: 'Tower A1',
    a2: 'Tower A2',
    a3: 'Tower A3',
    a4: 'Tower A4',    
    b1: 'Tower B1',
    b2: 'Tower B2',
    b3: 'Tower B3',
    b4: 'Tower B4',
    b5: 'Tower B5',
    b6: 'Tower B6',
    c1: 'Tower C1',
    c2: 'Tower C2',
    d1: 'Tower D1',
    d2: 'Tower D2',
  },
};

export const MANARATRESIDENCES3_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    manaratiii: 'Manarat\n Living 3',
    b1: 'Tower B1',
  },
};

export const ONESAADIYAT_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    onesaadiyat: 'Baccarat Residences Saadiyat',
    massena: 'Massena',
    zenith: 'Zénith',
  },
};

export const WILDS_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  propertyTypeDisplayNameMap: {
    'Standard Villas': 'Cassia Villas',
    'Premium Villas': 'Ravenna Residences',
    'Ultra Luxury Villas': 'Moringa Mansions',
    'Ultra Lux Villa': 'Moringa Mansion',
    'Standard': 'Cassia Villas',
    'Premium': 'Ravenna Residences',
    'Ultra Luxury': 'Moringa Mansions',
  },
  displayNameMap: {
    wilds: 'Wilds',
    p1: 'Dalma',
    p2: 'Naseem',
    p3: 'Cassia 6',
    p4: 'Cassia 5',
    p5: 'Nura',
    p6: 'Murjan',
    p7: 'Cassia 1',
    p8: 'Cassia 2',
    p9: 'Cassia 3 / 4',
  },
};

export const FAHIDBOTANICA_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    fahidbotanica: 'FahidBotanica',
    af4: 'AF4',
    af5: 'AF5',
  },
};

export const YALINKSLUXURY_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    yaslinksluxury: 'Waldorf Astoria Residences',
    b1: 'Residence 1',
    b2: 'Residence 2',
    b3: 'Residence 3',
  },
};

export const WOOLWICH_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.GBP,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: true,
  //externalRequestCallback: 'https://londonsquare.co.uk/developments/woolwich',
  externalRequestCallback:'',
  displayNameMap: {
    woolwich: 'Woolwich',
    woolwichtower: 'Woolwich Tower',
  },
  brochureDownloadAvailabilityMap: {
    woolwichtower: true,
  },
};

export const BROOKGREEN_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Variant, ViewConfigType.UnitView],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.GBP,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  //externalRequestCallback: 'https://fiftybrookgreen.co.uk/?woa#genericForm',
  externalRequestCallback: '',
  displayNameMap: {
    brookgreen: 'Brook Green',
    b1: 'Rosemont House',
    b2: 'Birchwood Place',
    b3: 'Oakmere Place',
    b4: 'Ashby House',
    b5: 'Mapleton Place',
  },
  brochureDownloadAvailabilityMap: {
    [PROJECT_BROCHURE_DOWNLOAD_KEY]: true,
    b1: true,
    b2: true,
    b3: true,
    b4: true,
    b5: true,
  },
};

export const WILLESDEN_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.GBP,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  //externalRequestCallback: 'https://londonsquare.co.uk/developments/willesden',
  externalRequestCallback:'',
  displayNameMap: {
    willesden: 'Willesden',
    b1: 'Tower B1',
    b2: 'Tower B2',
    b3: 'Tower B3',
    b4: 'Tower B4',
    b5: 'Tower B5',
    b6: 'Tower B6',
  },
};

export const NINEELMS_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.GBP,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    nineelms: 'Nine Elms',
    nineElms: 'Nine Elms',
    lsqnineelms: 'LSQ Nine Elms',
  },
  brochureDownloadAvailabilityMap: {
    lsqnineelms: true,
  },
};

export const COUNTYHALLKINGSTON_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Variant, ViewConfigType.UnitView],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.GBP,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: true,
  externalRequestCallback: 'https://countyhallkingston.co.uk/?woa#genericForm',
  //externalRequestCallback:'',
  displayNameMap: {
    countyhallkingston: 'County Hall Kingston',
    d1: 'Whittling Apartments',
    d2: 'Cornice Apartments',
    d3: 'Keystone House',
    d4: 'Ashlar House',
    d5: 'Portico House',
    d6: 'Tower D6',
    a1: 'Ebbstone House',
    a2: 'Riverton House',
    a3: 'Henmere House',
  },
  brochureDownloadAvailabilityMap: {
    [PROJECT_BROCHURE_DOWNLOAD_KEY]: true,
    a1: true,
    a2: true,
    a3: true,
    d1: true,
    d2: true,
    d3: true,
    d4: true,
    d5: true,
    d6: true,
  },
};

export const WIMBLEDONBRIDGEHOUSE_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.GBP,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: true,
  //externalRequestCallback: 'https://londonsquare.co.uk/developments/wimbledon',
  externalRequestCallback:'',
  displayNameMap: {
    wimbledonbridgehouse: 'Wimbledon Bridge House',
  },
  brochureDownloadAvailabilityMap: {
    wimbledonbridgehouse: true,
  },
};

export const RANSOMESWHARF_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Variant, ViewConfigType.UnitView],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.GBP,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: true,
  //externalRequestCallback: 'https://ransomeswharf.co.uk/',
  externalRequestCallback:'',
  displayNameMap: {
    ransomeswharf: 'RANSOMES WHARF',
    d1: 'Oakwood House',
    d2: 'Arbor House',
    d3: 'Tower C',
    d4: 'Foundry House',
    d5: 'Chancery House',
  },
};

export const SMDGARDENS_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Variant,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    smdgardens: 'SMD Gardens',
    cluster: 'Cluster',
  },
};

export const GARDENIABAY_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    views: 'Gardenia Views',
    terraces: 'Gardenia Terraces',
    bayviewresidences: 'Bay View Residences',
    gardenia: 'Gardenia Bay',
  },
};

export const SAMAYAS_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    samayas: 'Sama Yas',
    b1: 'Sama Yas 1',
    b2: 'Sama Yas 2',
    b3: 'Sama Yas 3',
  },
};

export const REEMANLIVING_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    'reemanliving': 'Reeman Living',
    'reemanliving-2': 'Reeman Living 2',
    '1a': 'Reeman Living 1A',
    '1b': 'Reeman Living 1B',
    '2a': 'Reeman Living 2A',
    '2b': 'Reeman Living 2B',
    '3a': 'Reeman Living 3A',
    '3b': 'Reeman Living 3B',
  },
};

export const MAYAN_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    mayan: 'Mayan',
    b1: 'Tower 1',
    b2: 'Tower 2',
    b3: 'Tower 3',
    b4: 'Tower 4',
  },
};

export const SUSTAINABLECITYYAS_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    sc: 'The Sustainable City',
    yn7: 'Townhouses',
    cr01: 'Condos 01',
    cr02: 'Condos 02',
    cr03: 'Condos 03',
    cr04: 'Condos 04',
    cr05: 'Condos 05',
    cr06: 'Condos 06',
    cr07: 'Condos 07',
    cr08: 'Condos 08',
    cr09: 'Condos 09',
    cr10: 'Condos 10',
    cr11: 'Condos 11',
    cr12: 'Condos 12',
    cr13: 'Condos 13',
    cr14: 'Condos 14',
    cr15: 'Condos 15',
    cr16: 'Condos 16',
    cr17: 'Condos 17',
    cr18: 'Condos 18',
    cr19: 'Condos 19',
    cr20: 'Condos 20',
    cr21: 'Condos 21',
    cr22: 'Condos 22',
    cr23: 'Condos 23',
    cr24: 'Condos 24',
    cr25: 'Condos 25',
    cr26: 'Condos 26',
    cr27: 'Condos 27',
    cr28: 'Condos 28',
    cr29: 'Condos 29',
    cr30: 'Condos 30',
    cr31: 'Condos 31',
    cr32: 'Condos 32',
    cr33: 'Condos 33',
    cr34: 'Condos 34',
    cr35: 'Condos 35',
    cr36: 'Condos 36',
    cr37: 'Condos 37',
    cr38: 'Condos 38',
    cr39: 'Condos 39',
    cr40: 'Condos 40',
    cr41: 'Condos 41',
    cr42: 'Condos 42',
    cr43: 'Condos 43',
    cr44: 'Condos 44',
    cr45: 'Condos 45',
    cr46: 'Condos 46',
    cr47: 'Condos 47',
    cr48: 'Condos 48',
    cr49: 'Condos 49',
    cr50: 'Condos 50',
    cr51: 'Condos 51',
    cr52: 'Condos 52',
    cr53: 'Condos 53',
    cr54: 'Condos 54',
    cr55: 'Condos 55',
    cr56: 'Condos 56',
    cr57: 'Condos 57',
    cr58: 'Condos 58',
    cr59: 'Condos 59',
    cr60: 'Condos 60',
    cr61: 'Condos 61',
    cr62: 'Condos 62',
    cr63: 'Condos 63',
    cr64: 'Condos 64',
    cr65: 'Condos 65',
    cr66: 'Condos 66',
    cr67: 'Condos 67',
    cr68: 'Condos 68',
    cr69: 'Condos 69',
    cr70: 'Condos 70',
    cr71: 'Condos 71',
    cr72: 'Condos 72',
    cr73: 'Condos 73',
    cr74: 'Condos 74',
    cr75: 'Condos 75',
    cr76: 'Condos 76',
    cr77: 'Condos 77',
    cr78: 'Condos 78',
    cr79: 'Condos 79',
    cr80: 'Condos 80',
    cr81: 'Condos 81',
    cr82: 'Condos 82',
    cr83: 'Condos 83',
    cr84: 'Condos 84',
    cr85: 'Condos 85',
    cr86: 'Condos 86',
  },
};

export const NOBURESIDENCES_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    noburesidences: 'Nobu Residences',
    b1: 'Nobu Residences 1',
    b2e: 'Nobu Residences 2 East',
    b2w: 'Nobu Residences 2 West',
  },
};

export const YASGOLFCOLLECTION_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    yasgolfcollection: 'Yas Golf Collection',
    b1: 'Furnished Apartments 1',
    b2: 'Furnished Apartments 2',
    b3: 'Furnished Apartments 3',
    b4: 'Furnished Apartments 4',
    a: 'Views A',
    b: 'Views B',
    c: 'Residences C',
    d: 'Residences D',
    e: 'Residences E',
    f: 'Views F',
    g: 'Views G',
    h: 'Clubhouse H',
    j: 'Clubhouse J',
  },
};

export const BALGHAIYLAM_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    balghaiylam: 'Balghaiylam',
    bag1: 'BAG1',
    bag2: 'BAG2',
    bag3: 'BAG3',
    bag4: 'BAG4',
    bag5: 'BAG5',
    bag6: 'BAG6',
  },
};

export const ALDEEM_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    aldeemtownhomes: 'Al Deem\n Townhomes',
    aldeem: 'Al Deem',
  },
};

export const YASPARKGATE_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {
    yasparkgate: 'Yas Park Gate',
    n2: 'N2',
  },
};

export const THESOURCETERRACES_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {thesourceterraces: 'The Source Terraces'},
};
export const YASACRES_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {
    'yasacres': 'Yasacres',
    'dahlias': 'Dahlias',
    'mangolias': 'Mangolias',
    'yasacres-dahlias': 'Yasacres The Dahlias',
    'yasacres-mangolias': 'Yasacres The Mangolias',
  },
  variantFloorCounts: {
    V_P_6B_F: 2,
    V_P_6BF_F: 2,
  },
};

export const YASLIVING_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    yasliving: 'Yas Living',
    b1: 'Tower B1',
    b2: 'Tower B2',
    b3: 'Tower B3',
  },
};

export const SAADIYATLAGOONS_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {
    lagoons: 'Saadiyat Lagoons',
    ethir: 'Ethir',
    alsidr: 'Al Sidr',
    alghaf: 'Al Ghaf',
  },
};

const YAS_PARK_VIEWS_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {yasparkviews: 'Yas Park Views'},
};
const LOUVRERESIDENCES_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {
    louvreresidences: 'Louvre Residences',
    r17: 'Un',
    r16: 'Deux',
    r15: 'Trois',
  },
};

export const NOYALUMA_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {
    noyaluma: 'NoyaLuma',
    n3: 'N3',
  },
};

export const NOYAVIVA_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {
    noyaviva: 'NoyaViva',
    n2: 'N2',
  },
};

const NOYA_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {
    noya: 'Noya',
    n1: 'N1',
    n2: 'N2',
  },
};

const FAYALREEMAN_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {
    alreeman2: 'Fay Al Reeman',
    n4: 'N4',
    n5a: 'N5A',
    n5b: 'N5B',
    n6: 'N6',
    n7: 'N7',
    n8: 'N8',
  },
};

const SAADIYAT_DUNES_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {
    saadiyatreserve: 'Saadiyat Reserve',
  },
};

export const NOURANLIVING_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {nouranliving: 'Nouran Living'},
};

export const THESOURCE_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {thesource: 'The Source'},
};

const THE_SOURCE_2_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {
    thesourceii: 'The Source II',
  },
};

export const THEROWSAADIYAT_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Interior, AreaTypes.Exterior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
    therowsaadiyat: 'The Row Saadiyat',
    b1: 'The Row One',
    b2: 'The Row Two',
    b3: 'The Row Three',
    b4: 'The Row Four',
    b5: 'The Row Five',
    b6: 'The Row Six',
    b7: 'The Row Seven',
  },
};

const THE_MANARAT_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {
    manarat: 'Manarat Living',
  },
};

export const MANARATLIVINGII_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {
    manaratii: 'Manarat Living II',
    b1: 'Tower B1',
  },
};
export const WILDS_RESIDENCES_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {
    thewildsresidences: 'The Wilds Residences',
    b1: 'B1',
    b2: 'B2',
    b3: 'B3',
    b4: 'B4',
    b5: 'B5',
    b6: 'B6',
  },
};

export const YASPARKPLACE_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Floorplan,
  exteriorViewConfigType: ViewConfigType.Unit,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: false,
  displayedAreas: [AreaTypes.Total, AreaTypes.Exterior, AreaTypes.Interior],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  displayNameMap: {
  },
};

export const ALGHADEERGARDENS_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: false,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Unit,
  interiorViewConfigTypes: [ViewConfigType.Unit],
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  showAlternativeAreaUnit: false,
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
}



export const PROJECT_CONFIGS: Record<string, IProjectConfig> = {
  verdes: VERDES_PROJECT_CONFIG,
  westminster: WESTMINSTER_PROJECT_CONFIG,
  haven: HAVEN_PROJECT_CONFIG,
  almarjan: ALMARJAN_PROJECT_CONFIG,
  athlon: ATHLON_PROJECT_CONFIG,
  risebyathlon: RISEBYATHLON_PROJECT_CONFIG,
  mamshapalm: MAMSHAPALM_PROJECT_CONFIG,
  mamshagarden: MAMSHAGARDEN_PROJECT_CONFIG,
  thearthouse: THEARTHOUSE_PROJECT_CONFIG,
  grove: GROVE_PROJECT_CONFIG,
  yasriva: YASRIVA_PROJECT_CONFIG,
  yasrivaresidences: YASRIVARESIDENCES_PROJECT_CONFIG,
  guggenheimmuseum: SCD_PROJECT_CONFIG,
  businessdistrict: SCD_PROJECT_CONFIG,
  fountaindistrict: SCD_PROJECT_CONFIG,
  grovedistrict: SCD_PROJECT_CONFIG,
  therowsaadiyat: THEROWSAADIYAT_PROJECT_CONFIG,
  artisandistrict: SCD_PROJECT_CONFIG,
  mamshadistrict: SCD_PROJECT_CONFIG,
  lifestyledistrict: SCD_PROJECT_CONFIG,
  pulsedistrict: SCD_PROJECT_CONFIG,
  abrahamicfamilyhouse: SCD_PROJECT_CONFIG,
  centerofcuriosity: SCD_PROJECT_CONFIG,
  louvre: SCD_PROJECT_CONFIG,
  manaratgallery: SCD_PROJECT_CONFIG,
  pier: SCD_PROJECT_CONFIG,
  zayedmuseum: SCD_PROJECT_CONFIG,
  naturalhistorymuseum: SCD_PROJECT_CONFIG,
  waterfrontpromenade: FAHIDISLAND_PROJECT_CONFIG,
  coraldrive: FAHIDISLAND_PROJECT_CONFIG,
  theberm: FAHIDISLAND_PROJECT_CONFIG,
  twickenhamsquare: TWICKENHAMSQUARE_PROJECT_CONFIG,
  twickenhamgreen: TWICKENHAMGREEN_PROJECT_CONFIG,
  fayaalsaadiyat: FAYAALSAADIYAT_PROJECT_CONFIG,
  wandsworthcommon: WANDSWORTHCOMMON_PROJECT_CONFIG,
  fountainviewresidences: FOUNTAINVIEWRESIDENCES_PROJECT_CONFIG,
  fayaalsaadiyatii: FAYAALSAADIYATII_PROJECT_CONFIG,
  fahidbeachresidences: FAHIDBEACHRESIDENCES_PROJECT_CONFIG,
  fahidbeachterraces: FAHIDBEACHTERRACES_PROJECT_CONFIG,
  thebeachhouse: THEBEACHHOUSE_PROJECT_CONFIG,
  thebeachhouse2: THEBEACHHOUSE2_PROJECT_CONFIG,
  manaratiii: MANARATRESIDENCES3_PROJECT_CONFIG,
  onesaadiyat: ONESAADIYAT_PROJECT_CONFIG,
  fahidbotanica: FAHIDBOTANICA_PROJECT_CONFIG,
  wilds: WILDS_PROJECT_CONFIG,
  thewildsresidences: WILDS_RESIDENCES_PROJECT_CONFIG,
  yaslinksluxury: YALINKSLUXURY_PROJECT_CONFIG,
  yasliving: YASLIVING_PROJECT_CONFIG,
  ransomeswharf: RANSOMESWHARF_PROJECT_CONFIG,
  woolwich: WOOLWICH_PROJECT_CONFIG,
  brookgreen: BROOKGREEN_PROJECT_CONFIG,
  willesden: WILLESDEN_PROJECT_CONFIG,
  nineelms: NINEELMS_PROJECT_CONFIG,
  countyhallkingston: COUNTYHALLKINGSTON_PROJECT_CONFIG,
  wimbledonbridgehouse: WIMBLEDONBRIDGEHOUSE_PROJECT_CONFIG,
  smdgardens: SMDGARDENS_PROJECT_CONFIG,
  gardenia: GARDENIABAY_PROJECT_CONFIG,
  samayas: SAMAYAS_PROJECT_CONFIG,
  noburesidences: NOBURESIDENCES_PROJECT_CONFIG,
  yasgolfcollection: YASGOLFCOLLECTION_PROJECT_CONFIG,
  balghaiylam: BALGHAIYLAM_PROJECT_CONFIG,
  thesourceterraces: THESOURCETERRACES_PROJECT_CONFIG,
  yasparkviews: YAS_PARK_VIEWS_PROJECT_CONFIG,
  yasparkgate: YASPARKGATE_PROJECT_CONFIG,
  yasacres: YASACRES_PROJECT_CONFIG,
  lagoons: SAADIYATLAGOONS_PROJECT_CONFIG,
  noyaluma: NOYALUMA_PROJECT_CONFIG,
  louvreresidences: LOUVRERESIDENCES_PROJECT_CONFIG,
  mayan: MAYAN_PROJECT_CONFIG,
  sc: SUSTAINABLECITYYAS_PROJECT_CONFIG,
  noya: NOYA_PROJECT_CONFIG,
  alreeman2: FAYALREEMAN_PROJECT_CONFIG,
  reemanliving: REEMANLIVING_PROJECT_CONFIG,
  saadiyatreserve: SAADIYAT_DUNES_PROJECT_CONFIG,
  noyaviva: NOYAVIVA_PROJECT_CONFIG,
  nouranliving: NOURANLIVING_PROJECT_CONFIG,
  thesourceii: THE_SOURCE_2_PROJECT_CONFIG,
  thesource: THESOURCE_PROJECT_CONFIG,
  aldeemtownhomes: ALDEEM_PROJECT_CONFIG,
  manarat: THE_MANARAT_PROJECT_CONFIG,
  manaratii: MANARATLIVINGII_PROJECT_CONFIG,
  yasparkplace: YASPARKPLACE_PROJECT_CONFIG,
  alghadeergardens: ALGHADEERGARDENS_PROJECT_CONFIG,
};

export const DEFAULT_PROJECT_CONFIG: IProjectConfig = {
  hasSchemes: true,
  hasPoolOption: false,
  hasPodOption: false,
  unitDefaultState: UnitStates.Interior,
  exteriorViewConfigType: ViewConfigType.Variant,
  floorplanViewConfigType: ViewConfigType.Variant,
  hasExteriorViews: true,
  displayedAreas: [AreaTypes.Total],
  currencyCode: CurrencyCodes.AED,
  areaUnit: AreaUnits.M2,
  showAlternativeAreaUnit: false,
  externalRequestCallback: '',
  displayNameMap: {},
  brochureDownloadAvailabilityMap: {},
  variantsWithSchemes: [],
};

export const hasProjectBrochureDownload = (
  projectCode?: string,
  towerCode?: string
) => {
  const projectKey = normalizeBrochureCode(projectCode);

  if (!projectKey) {
    return false;
  }

  const brochureKey =
    normalizeBrochureCode(towerCode) || PROJECT_BROCHURE_DOWNLOAD_KEY;
  const projectConfig = PROJECT_CONFIGS[projectKey];

  return projectConfig?.brochureDownloadAvailabilityMap?.[brochureKey] === true;
};
