export const CAMERA_CONTROLS_CONSTANTS = {
  MIN_VERTICAL_ANGLE: Math.PI - 0.1,
  MAX_VERTICAL_ANGLE: 0.1,
  MOUSE_SENSITIVITY_X: 0.5,
  MOUSE_SENSITIVITY_Y: 0.3,
  TOUCH_SENSITIVITY_X: 2,
  TOUCH_SENSITIVITY_Y: 1.1,
};
